#define TOTAL_IC 1;
void LTC_setup();
void LTC_initialize();
uint16_t LTC_cell_voltage_meas();
uint16_t LTC_temp_voltage_meas();
void print_menu();
void run_command(uint32_t cmd);
void init_cfg();
void print_cells();
void print_temp();
void print_config();
void print_rxconfig();
void serial_print_hex(uint8_t data);
